# docker-compose.yml
version: "3.8"
services:
  
  php:
    container_name: avdevs-backend
    build:
        context: ./src
        dockerfile: Dockerfile
    ports:
      - '9011:3000'
    command: "php artisan serve --host=0.0.0.0 --port=3000"
    volumes:
      - './src:/avdevs/'
    env_file:
      - './src/.env'  

  composer:
    container_name: avdevs-composer
    image: composer/composer
    volumes:
      - ./src/:/usr/local/apache2/htdocs/
    working_dir: /usr/local/apache2/htdocs/
    command: install    

  mysql:
    image: mysql:8.0.27
    container_name: avdevs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: avdevstest
      MYSQL_USER: admin
      MYSQL_PASSWORD: 'password'
    ports:
      - "3311:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: avdevs-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 9012:80

  # redis:
  #   image: redis:4.0
  #   container_name: avdevs-app_redis
  #   ports:
  #     - "6382:6379"


  
